services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.39.11
    ports:
      - "8090:8090"
    volumes:
      - ./pb_migrations:/pb_migrations
      - pb_data:/pb_data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8090/api/health"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pb_data:
