/// <reference path="../pb_data/types.d.ts" />

// Storage Boxes app schema. Generated by scripts/pb-snapshot.py — do not edit by hand.
//
// Imported in extend mode (deleteMissing = false), so collections belonging to
// other apps on a shared PocketBase instance are never touched.
//
// `apps` and `app_memberships` are shared multi-app collections: they are only
// created when absent, never overwritten on an instance that already has them.

const SHARED = [
  {
    "id": "pbc_923867626",
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "name": "apps",
    "type": "base",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text2324736937",
        "max": 0,
        "min": 0,
        "name": "key",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1579384326",
        "max": 0,
        "min": 0,
        "name": "name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": true,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text3252000302",
        "max": 0,
        "min": 0,
        "name": "subdomain",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "help": "",
        "hidden": false,
        "id": "bool1260321794",
        "name": "active",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "convertURLs": false,
        "help": "",
        "hidden": false,
        "id": "editor1843675174",
        "maxSize": 0,
        "name": "description",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "editor"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "indexes": [
      "CREATE UNIQUE INDEX `idx_PKqLpArPgL` ON `apps` (`key`)"
    ],
    "system": false
  },
  {
    "id": "pbc_2985528408",
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "name": "app_memberships",
    "type": "base",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "help": "",
        "hidden": false,
        "id": "relation2375276105",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "user",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_923867626",
        "help": "",
        "hidden": false,
        "id": "relation3379458255",
        "maxSelect": 999,
        "minSelect": 0,
        "name": "app",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "help": "",
        "hidden": false,
        "id": "select1466534506",
        "maxSelect": 1,
        "name": "role",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "select",
        "values": [
          "owner",
          "admin",
          "member",
          "readonly"
        ]
      },
      {
        "help": "",
        "hidden": false,
        "id": "bool1358543748",
        "name": "enabled",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "indexes": [],
    "system": false
  }
]

const STORAGE = [
  {
    "id": "pbc_822680373",
    "listRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "viewRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "createRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "updateRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "deleteRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true &&\n(\n  @request.auth.app_memberships_via_user.role ?= \"owner\" ||\n  @request.auth.app_memberships_via_user.role ?= \"admin\"\n)",
    "name": "storage_tags",
    "type": "base",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1579384326",
        "max": 0,
        "min": 0,
        "name": "name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1716930793",
        "max": 0,
        "min": 0,
        "name": "color",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "help": "",
        "hidden": false,
        "id": "relation3725765462",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "created_by",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "indexes": [
      "CREATE UNIQUE INDEX `idx_182tx1ekaf` ON `storage_tags` (`name`)"
    ],
    "system": false
  },
  {
    "id": "pbc_1225868984",
    "listRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "viewRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "createRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true && @request.body.created_by = @request.auth.id",
    "updateRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true &&\n(\n  created_by = @request.auth.id ||\n  (@request.auth.storage_box_permissions_via_user.box ?= id &&\n   @request.auth.storage_box_permissions_via_user.role ?= \"editor\")\n) && @request.body.created_by:isset = false",
    "deleteRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true &&\ncreated_by = @request.auth.id",
    "name": "storage_boxes",
    "type": "base",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text724990059",
        "max": 0,
        "min": 0,
        "name": "title",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "convertURLs": false,
        "help": "",
        "hidden": false,
        "id": "editor1843675174",
        "maxSize": 0,
        "name": "description",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "editor"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1587448267",
        "max": 0,
        "min": 0,
        "name": "location",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "help": "",
        "hidden": false,
        "id": "file3760176746",
        "maxSelect": 15,
        "maxSize": 0,
        "mimeTypes": [
          "image/png",
          "image/vnd.mozilla.apng",
          "image/jpeg",
          "image/webp",
          "image/heic",
          "image/heic-sequence"
        ],
        "name": "images",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1520847447",
        "max": 0,
        "min": 0,
        "name": "qr_id",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": true,
        "system": false,
        "type": "text"
      },
      {
        "help": "",
        "hidden": false,
        "id": "select2063623452",
        "maxSelect": 1,
        "name": "status",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "active",
          "archived"
        ]
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_822680373",
        "help": "",
        "hidden": false,
        "id": "relation1874629670",
        "maxSelect": 999,
        "minSelect": 0,
        "name": "tags",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "help": "",
        "hidden": false,
        "id": "relation3725765462",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "created_by",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "indexes": [
      "CREATE UNIQUE INDEX `idx_LvcdU8J6CX` ON `storage_boxes` (`qr_id`)"
    ],
    "system": false
  },
  {
    "id": "pbc_1711152412",
    "listRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "viewRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "createRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true\n&& @request.body.created_by = @request.auth.id\n&& (\n  @request.body.box.created_by = @request.auth.id ||\n  (@request.auth.storage_box_permissions_via_user.box ?= @request.body.box &&\n   @request.auth.storage_box_permissions_via_user.role ?= \"editor\")\n)",
    "updateRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true &&\n(\n  box.created_by = @request.auth.id ||\n  (@request.auth.storage_box_permissions_via_user.box ?= box.id &&\n   @request.auth.storage_box_permissions_via_user.role ?= \"editor\")\n) && @request.body.created_by:isset = false",
    "deleteRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true &&\n(\n  box.created_by = @request.auth.id ||\n  (@request.auth.storage_box_permissions_via_user.box ?= box.id &&\n   @request.auth.storage_box_permissions_via_user.role ?= \"editor\")\n)",
    "name": "storage_items",
    "type": "base",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_1225868984",
        "help": "",
        "hidden": false,
        "id": "relation145311802",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "box",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text724990059",
        "max": 0,
        "min": 0,
        "name": "title",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": true,
        "system": false,
        "type": "text"
      },
      {
        "convertURLs": false,
        "help": "",
        "hidden": false,
        "id": "editor1843675174",
        "maxSize": 0,
        "name": "description",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "editor"
      },
      {
        "convertURLs": false,
        "help": "",
        "hidden": false,
        "id": "editor18589324",
        "maxSize": 0,
        "name": "notes",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "editor"
      },
      {
        "help": "",
        "hidden": false,
        "id": "file3760176746",
        "maxSelect": 99,
        "maxSize": 0,
        "mimeTypes": [
          "image/png",
          "image/vnd.mozilla.apng",
          "image/jpeg",
          "image/webp",
          "image/heic",
          "image/heic-sequence"
        ],
        "name": "images",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_822680373",
        "help": "",
        "hidden": false,
        "id": "relation1874629670",
        "maxSelect": 999,
        "minSelect": 0,
        "name": "tags",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "help": "",
        "hidden": false,
        "id": "relation3725765462",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "created_by",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "indexes": [],
    "system": false
  },
  {
    "id": "pbc_3795457256",
    "listRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "viewRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "createRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true && @request.body.user = @request.auth.id",
    "updateRule": "@request.auth.id != \"\" &&\nuser = @request.auth.id &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true && @request.body.user:isset = false",
    "deleteRule": "@request.auth.id != \"\" &&\nuser = @request.auth.id &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "name": "storage_comments",
    "type": "base",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_1711152412",
        "help": "",
        "hidden": false,
        "id": "relation521872670",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "item",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "help": "",
        "hidden": false,
        "id": "relation2375276105",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "user",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text999008199",
        "max": 0,
        "min": 0,
        "name": "text",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": true,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "indexes": [],
    "system": false
  },
  {
    "id": "pbc_3180270093",
    "listRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "viewRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "createRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true &&\n@request.body.created_by = @request.auth.id",
    "updateRule": "@request.auth.id != \"\" &&\ncreated_by = @request.auth.id &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true && @request.body.created_by:isset = false",
    "deleteRule": "@request.auth.id != \"\" &&\ncreated_by = @request.auth.id &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "name": "storage_item_voice_notes",
    "type": "base",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_1711152412",
        "help": "",
        "hidden": false,
        "id": "relation521872670",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "item",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "help": "",
        "hidden": false,
        "id": "file410859157",
        "maxSelect": 1,
        "maxSize": 0,
        "mimeTypes": [
          "audio/mpeg",
          "audio/mp4"
        ],
        "name": "audio",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text245846248",
        "max": 0,
        "min": 0,
        "name": "label",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "help": "",
        "hidden": false,
        "id": "relation3725765462",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "created_by",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "indexes": [],
    "system": false
  },
  {
    "id": "pbc_1830113085",
    "listRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "viewRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "createRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true &&\nbox.created_by = @request.auth.id",
    "updateRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true &&\nbox.created_by = @request.auth.id",
    "deleteRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true &&\nbox.created_by = @request.auth.id",
    "name": "storage_box_permissions",
    "type": "base",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_1225868984",
        "help": "",
        "hidden": false,
        "id": "relation145311802",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "box",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "help": "",
        "hidden": false,
        "id": "relation2375276105",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "user",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "help": "",
        "hidden": false,
        "id": "select1466534506",
        "maxSelect": 1,
        "name": "role",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "editor"
        ]
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "indexes": [],
    "system": false
  },
  {
    "id": "pbc_3601393757",
    "listRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "viewRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "name": "storage_app_users",
    "type": "view",
    "fields": [
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 0,
        "min": 0,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1579384326",
        "max": 0,
        "min": 0,
        "name": "name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1466534506",
        "max": 0,
        "min": 0,
        "name": "role",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      }
    ],
    "indexes": [],
    "system": false,
    "viewQuery": "SELECT id, CAST(name AS TEXT) AS name, CAST((CASE role_rank WHEN 1 THEN 'owner' WHEN 2 THEN 'admin' WHEN 3 THEN 'member' ELSE 'readonly' END) AS TEXT) AS role FROM ( SELECT u.id AS id, u.name AS name, MIN(CASE m.role WHEN 'owner' THEN 1 WHEN 'admin' THEN 2 WHEN 'member' THEN 3 ELSE 4 END) AS role_rank FROM users u JOIN app_memberships m ON m.user = u.id JOIN apps a ON a.id IN (SELECT value FROM json_each(m.app)) WHERE m.enabled = TRUE AND a.key = 'storage' GROUP BY u.id, u.name )"
  },
  {
    "id": "pbc_2659375862",
    "listRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "viewRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "name": "storage_report_box_fill",
    "type": "view",
    "fields": [
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 0,
        "min": 0,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "_clone_KCpT",
        "max": 0,
        "min": 0,
        "name": "title",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "_clone_B3iB",
        "max": 0,
        "min": 0,
        "name": "location",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "help": "",
        "hidden": false,
        "id": "_clone_padc",
        "maxSelect": 1,
        "name": "status",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "active",
          "archived"
        ]
      },
      {
        "help": "",
        "hidden": false,
        "id": "number2944294834",
        "max": null,
        "min": null,
        "name": "item_count",
        "onlyInt": true,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "help": "",
        "hidden": false,
        "id": "number1065894869",
        "max": null,
        "min": null,
        "name": "photo_count",
        "onlyInt": true,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      }
    ],
    "indexes": [],
    "system": false,
    "viewQuery": "SELECT b.id AS id, b.title AS title, b.location AS location, b.status AS status, CAST((SELECT COUNT(*) FROM storage_items i WHERE i.box = b.id) AS INTEGER) AS item_count, CAST((SELECT COUNT(*) FROM storage_items i WHERE i.box = b.id AND i.images != '' AND i.images != '[]') AS INTEGER) AS photo_count FROM storage_boxes b"
  },
  {
    "id": "pbc_1966404343",
    "listRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "viewRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "name": "storage_report_growth",
    "type": "view",
    "fields": [
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 0,
        "min": 0,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text2394296326",
        "max": 0,
        "min": 0,
        "name": "month",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "help": "",
        "hidden": false,
        "id": "number575394000",
        "max": null,
        "min": null,
        "name": "boxes_created",
        "onlyInt": true,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "help": "",
        "hidden": false,
        "id": "number3468554169",
        "max": null,
        "min": null,
        "name": "items_created",
        "onlyInt": true,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      }
    ],
    "indexes": [],
    "system": false,
    "viewQuery": "SELECT REPLACE(m.month, '-', '') AS id, CAST(m.month AS TEXT) AS month, CAST((SELECT COUNT(*) FROM storage_boxes b WHERE strftime('%Y-%m', b.created) = m.month) AS INTEGER) AS boxes_created, CAST((SELECT COUNT(*) FROM storage_items i WHERE strftime('%Y-%m', i.created) = m.month) AS INTEGER) AS items_created FROM ( SELECT DISTINCT CAST(strftime('%Y-%m', created) AS TEXT) AS month FROM storage_boxes UNION SELECT DISTINCT CAST(strftime('%Y-%m', created) AS TEXT) AS month FROM storage_items ) m ORDER BY m.month"
  },
  {
    "id": "pbc_328497782",
    "listRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "viewRule": "@request.auth.id != \"\" &&\n@request.auth.app_memberships_via_user.app.key ?= \"storage\" &&\n@request.auth.app_memberships_via_user.enabled ?= true",
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "name": "storage_report_tag_usage",
    "type": "view",
    "fields": [
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 0,
        "min": 0,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "_clone_jE05",
        "max": 0,
        "min": 0,
        "name": "name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "_clone_lVjZ",
        "max": 0,
        "min": 0,
        "name": "color",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "help": "",
        "hidden": false,
        "id": "number4243822730",
        "max": null,
        "min": null,
        "name": "box_count",
        "onlyInt": true,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "help": "",
        "hidden": false,
        "id": "number2944294834",
        "max": null,
        "min": null,
        "name": "item_count",
        "onlyInt": true,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      }
    ],
    "indexes": [],
    "system": false,
    "viewQuery": "SELECT t.id AS id, t.name AS name, t.color AS color, CAST((SELECT COUNT(*) FROM storage_boxes b WHERE EXISTS (SELECT 1 FROM json_each(b.tags) WHERE value = t.id)) AS INTEGER) AS box_count, CAST((SELECT COUNT(*) FROM storage_items i WHERE EXISTS (SELECT 1 FROM json_each(i.tags) WHERE value = t.id)) AS INTEGER) AS item_count FROM storage_tags t"
  }
]

migrate((app) => {
  const toImport = []

  for (let i = 0; i < SHARED.length; i++) {
    try {
      app.findCollectionByNameOrId(SHARED[i].name)
    } catch (err) {
      toImport.push(SHARED[i])
    }
  }

  for (let i = 0; i < STORAGE.length; i++) {
    toImport.push(STORAGE[i])
  }

  app.importCollections(toImport, false)

  // The app gates every rule on an enabled membership referencing this row.
  try {
    app.findFirstRecordByFilter("apps", "key = 'storage'")
  } catch (err) {
    const apps = app.findCollectionByNameOrId("apps")
    app.save(new Record(apps, {
      key: "storage",
      name: "Storage Boxes",
      active: true,
    }))
  }
}, (app) => {
  // Reverse dependency order. Shared collections are intentionally left alone.
  const names = [
  "storage_report_tag_usage",
  "storage_report_growth",
  "storage_report_box_fill",
  "storage_app_users",
  "storage_box_permissions",
  "storage_item_voice_notes",
  "storage_comments",
  "storage_items",
  "storage_boxes",
  "storage_tags"
]

  for (let i = 0; i < names.length; i++) {
    try {
      app.delete(app.findCollectionByNameOrId(names[i]))
    } catch (err) {
      // already gone
    }
  }
})
