#!/usr/bin/env python3
"""Regenerate pb_migrations/<ts>_storage_schema.js from a live PocketBase.

Usage: python3 scripts/pb-snapshot.py [base_url]

Prompts for superuser credentials, reads the current collection definitions,
and rewrites the baseline schema migration. Only storage_* plus the shared
apps/app_memberships collections are captured; everything else on the instance
is ignored.
"""
import getpass
import json
import os
import re
import sys
import urllib.error
import urllib.request

MIGRATION = "pb_migrations/1787154450_storage_schema.js"
ORDER = ["storage_tags", "storage_boxes", "storage_items", "storage_comments",
         "storage_item_voice_notes", "storage_box_permissions"]
SHARED = ["apps", "app_memberships"]


# Cloudflare's Browser Integrity Check 403s the default Python-urllib agent
# (error 1010), so every request goes out with a browser-shaped UA.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36")


def post(url, payload, token=None):
    body = json.dumps(payload).encode()
    req = urllib.request.Request(url, data=body, method="POST",
                                 headers={"Content-Type": "application/json",
                                          "User-Agent": UA})
    if token:
        req.add_header("Authorization", token)
    with urllib.request.urlopen(req) as r:
        return json.load(r)


def get(url, token):
    req = urllib.request.Request(url, headers={"Authorization": token,
                                               "User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return json.load(r)


def main():
    base = (sys.argv[1] if len(sys.argv) > 1 else "http://localhost:8090").rstrip("/")
    print(f"PocketBase: {base}")
    identity = input("Superuser email: ")
    password = getpass.getpass("Superuser password: ")

    try:
        auth = post(f"{base}/api/collections/_superusers/auth-with-password",
                    {"identity": identity, "password": password})
    except urllib.error.HTTPError as e:
        sys.exit(f"auth failed: {e.code} {e.read().decode()[:200]}")
    token = auth["token"]

    items = get(f"{base}/api/collections?perPage=200", token)["items"]
    by_name = {c["name"]: c for c in items
               if c["name"].startswith("storage_") or c["name"] in SHARED}

    missing = [n for n in SHARED if n not in by_name]
    if missing:
        sys.exit(f"instance is missing shared collections: {', '.join(missing)}")

    # created/updated are per-instance metadata; keeping them makes every
    # re-snapshot diff on timestamps and hides real schema changes.
    for c in by_name.values():
        c.pop("created", None)
        c.pop("updated", None)

    storage = [by_name[n] for n in ORDER if n in by_name]
    storage += [by_name[n] for n in sorted(by_name)
                if n.startswith("storage_") and n not in ORDER]
    shared = [by_name[n] for n in SHARED]

    body = TEMPLATE.format(
        shared=json.dumps(shared, indent=2),
        storage=json.dumps(storage, indent=2),
        down=json.dumps([c["name"] for c in reversed(storage)], indent=2),
    )
    os.makedirs("pb_migrations", exist_ok=True)
    with open(MIGRATION, "w") as f:
        f.write(body)

    print(f"\nwrote {MIGRATION}")
    for c in storage + shared:
        idx = len(c.get("indexes") or [])
        print(f"  {c['name']:26} {len(c['fields'])} fields, {idx} index(es)")


TEMPLATE = '''/// <reference path="../pb_data/types.d.ts" />

// Storage Boxes app schema. Generated by scripts/pb-snapshot.py — do not edit by hand.
//
// Imported in extend mode (deleteMissing = false), so collections belonging to
// other apps on a shared PocketBase instance are never touched.
//
// `apps` and `app_memberships` are shared multi-app collections: they are only
// created when absent, never overwritten on an instance that already has them.

const SHARED = {shared}

const STORAGE = {storage}

migrate((app) => {{
  const toImport = []

  for (let i = 0; i < SHARED.length; i++) {{
    try {{
      app.findCollectionByNameOrId(SHARED[i].name)
    }} catch (err) {{
      toImport.push(SHARED[i])
    }}
  }}

  for (let i = 0; i < STORAGE.length; i++) {{
    toImport.push(STORAGE[i])
  }}

  app.importCollections(toImport, false)

  // The app gates every rule on an enabled membership referencing this row.
  try {{
    app.findFirstRecordByFilter("apps", "key = 'storage'")
  }} catch (err) {{
    const apps = app.findCollectionByNameOrId("apps")
    app.save(new Record(apps, {{
      key: "storage",
      name: "Storage Boxes",
      active: true,
    }}))
  }}
}}, (app) => {{
  // Reverse dependency order. Shared collections are intentionally left alone.
  const names = {down}

  for (let i = 0; i < names.length; i++) {{
    try {{
      app.delete(app.findCollectionByNameOrId(names[i]))
    }} catch (err) {{
      // already gone
    }}
  }}
}})
'''

if __name__ == "__main__":
    main()
